#include "pch.h"
#include "Measure.h"

using namespace WBFL::Units;
namespace py = pybind11;

void export_measure_types(py::module_& m)
{
   py::class_<Measure>(m,"Measure")
      .def_readonly_static("Kilogram",&Measure::Kilogram)
      .def_readonly_static("Gram", &Measure::Gram)
      .def_readonly_static("MetricTon", &Measure::MetricTon)
      .def_readonly_static("Slug", &Measure::Slug)
      .def_readonly_static("PoundMass", &Measure::PoundMass)
      .def_readonly_static("KSlug", &Measure::KSlug)
      .def_readonly_static("_12Slug", &Measure::_12Slug)
      .def_readonly_static("_12KSlug", &Measure::_12KSlug)
      .def_readonly_static("KgPerMeter", &Measure::KgPerMeter)
      .def_readonly_static("LbmPerFeet", &Measure::LbmPerFeet)
      .def_readonly_static("SlugPerFeet", &Measure::SlugPerFeet)
      .def_readonly_static("LbfPerFeet", &Measure::LbfPerFeet)
      .def_readonly_static("Meter",&Measure::Meter)
      .def_readonly_static("Millimeter", &Measure::Millimeter)
      .def_readonly_static("Centimeter", &Measure::Centimeter)
      .def_readonly_static("Kilometer", &Measure::Kilometer)
      .def_readonly_static("Feet", &Measure::Feet)
      .def_readonly_static("USSurveyFoot", &Measure::USSurveyFoot)
      .def_readonly_static("Inch", &Measure::Inch)
      .def_readonly_static("Mile", &Measure::Mile)
      .def_readonly_static("Yard", &Measure::Yard)
      .def_readonly_static("USSurveyYard", &Measure::USSurveyYard)
      .def_readonly_static("Meter2", &Measure::Meter2)
      .def_readonly_static("Millimeter2", &Measure::Millimeter2)
      .def_readonly_static("Centimeter2", &Measure::Centimeter2)
      .def_readonly_static("Kilometer2", &Measure::Kilometer2)
      .def_readonly_static("Feet2", &Measure::Feet2)
      .def_readonly_static("Inch2", &Measure::Inch2)
      .def_readonly_static("Mile2", &Measure::Mile2)
      .def_readonly_static("Yard2", &Measure::Yard2)
      .def_readonly_static("Meter3", &Measure::Meter3)
      .def_readonly_static("Millimeter3", &Measure::Millimeter3)
      .def_readonly_static("Centimeter3", &Measure::Centimeter3)
      .def_readonly_static("Kilometer3", &Measure::Kilometer3)
      .def_readonly_static("Feet3", &Measure::Feet3)
      .def_readonly_static("Inch3", &Measure::Inch3)
      .def_readonly_static("Mile3", &Measure::Mile3)
      .def_readonly_static("Yard3", &Measure::Yard3)
      .def_readonly_static("Meter4", &Measure::Meter4)
      .def_readonly_static("Millimeter4", &Measure::Millimeter4)
      .def_readonly_static("Centimeter4", &Measure::Centimeter4)
      .def_readonly_static("Kilometer4", &Measure::Kilometer4)
      .def_readonly_static("Feet4", &Measure::Feet4)
      .def_readonly_static("Inch4", &Measure::Inch4)
      .def_readonly_static("Mile4", &Measure::Mile4)
      .def_readonly_static("Yard4", &Measure::Yard4)
      .def_readonly_static("Meter2PerMeter", &Measure::Meter2PerMeter)
      .def_readonly_static("Millimeter2PerMillimeter", &Measure::Millimeter2PerMillimeter)
      .def_readonly_static("Millimeter2PerMeter", &Measure::Millimeter2PerMeter)
      .def_readonly_static("Feet2PerFoot", &Measure::Feet2PerFoot)
      .def_readonly_static("Inch2PerInch", &Measure::Inch2PerInch)
      .def_readonly_static("Inch2PerFoot", &Measure::Inch2PerFoot)
      .def_readonly_static("PerMeter", &Measure::PerMeter)
      .def_readonly_static("PerMillimeter", &Measure::PerMillimeter)
      .def_readonly_static("PerInch", &Measure::PerInch)
      .def_readonly_static("PerFeet", &Measure::PerFeet)
      .def_readonly_static("Second", &Measure::Second)
      .def_readonly_static("Minute", &Measure::Minute)
      .def_readonly_static("Hour", &Measure::Hour)
      .def_readonly_static("Day", &Measure::Day)
      .def_readonly_static("Celsius", &Measure::Celsius)
      .def_readonly_static("Fahrenheit", &Measure::Fahrenheit)
      .def_readonly_static("Radian", &Measure::Radian)
      .def_readonly_static("Degree", &Measure::Degree)
      .def_readonly_static("Pa", &Measure::Pa)
      .def_readonly_static("kPa", &Measure::kPa)
      .def_readonly_static("MPa", &Measure::MPa)
      .def_readonly_static("PSI", &Measure::PSI)
      .def_readonly_static("PSF", &Measure::PSF)
      .def_readonly_static("KSI", &Measure::KSI)
      .def_readonly_static("KSF", &Measure::KSF)
      .def_readonly_static("NewtonPerMeter3", &Measure::NewtonPerMeter3)
      .def_readonly_static("PCI", &Measure::PCI)
      .def_readonly_static("PCF", &Measure::PCF)
      .def_readonly_static("KgPerMeter3", &Measure::KgPerMeter3)
      .def_readonly_static("LbmPerFeet3", &Measure::LbmPerFeet3)
      .def_readonly_static("SlugPerFeet3", &Measure::SlugPerFeet3)
      .def_readonly_static("LbfPerFeet3", &Measure::LbfPerFeet3)
      .def_readonly_static("KipPerFeet3", &Measure::KipPerFeet3)
      .def_readonly_static("Newton", &Measure::Newton)
      .def_readonly_static("Kilonewton", &Measure::Kilonewton)
      .def_readonly_static("Pound", &Measure::Pound)
      .def_readonly_static("Kip", &Measure::Kip)
      .def_readonly_static("Ton", &Measure::Ton)
      .def_readonly_static("NewtonPerMeter", &Measure::NewtonPerMeter)
      .def_readonly_static("KilonewtonPerMeter", &Measure::KilonewtonPerMeter)
      .def_readonly_static("NewtonPerMillimeter", &Measure::NewtonPerMillimeter)
      .def_readonly_static("LbfPerFoot", &Measure::LbfPerFoot)
      .def_readonly_static("LbfPerInch", &Measure::LbfPerInch)
      .def_readonly_static("KipPerFoot", &Measure::KipPerFoot)
      .def_readonly_static("KipPerInch", &Measure::KipPerInch)
      .def_readonly_static("NewtonMeter", &Measure::NewtonMeter)
      .def_readonly_static("KilonewtonMeter", &Measure::KilonewtonMeter)
      .def_readonly_static("NewtonMillimeter", &Measure::NewtonMillimeter)
      .def_readonly_static("InchLbf", &Measure::InchLbf)
      .def_readonly_static("KipFeet", &Measure::KipFeet)
      .def_readonly_static("KipInch", &Measure::KipInch)
      .def_readonly_static("NewtonMeterPerRadian", &Measure::NewtonMeterPerRadian)
      .def_readonly_static("KiloNewtonMeterPerRadian", &Measure::KiloNewtonMeterPerRadian)
      .def_readonly_static("KipInchPerRadian", &Measure::KipInchPerRadian)
      .def_readonly_static("KipFeetPerRadian", &Measure::KipFeetPerRadian)
      .def_readonly_static("SqrtPa", &Measure::SqrtPa)
      .def_readonly_static("SqrtMPa", &Measure::SqrtMPa)
      .def_readonly_static("SqrtKSI", &Measure::SqrtKSI)
      .def_readonly_static("MeterPerSec2", &Measure::MeterPerSec2)
      .def_readonly_static("FeetPerSec2",&Measure::FeetPerSec2)
      .def_readonly_static("KipInch2", &Measure::KipInch2)
      .def_readonly_static("KipFoot2", &Measure::KipFoot2)
      .def_readonly_static("LbfInch2", &Measure::LbfInch2)
      .def_readonly_static("LbfFoot2", &Measure::LbfFoot2)
      .def_readonly_static("NewtonMeter2", &Measure::NewtonMeter2)
      .def_readonly_static("NewtonMillimeter2", &Measure::NewtonMillimeter2)
      .def_readonly_static("KilonewtonMeter2", &Measure::KilonewtonMeter2)
      .def_readonly_static("KilometerPerHour", &Measure::KilometerPerHour)
      .def_readonly_static("MeterPerSecond", &Measure::MeterPerSecond)
      .def_readonly_static("MilePerHour", &Measure::MilePerHour)
      .def_readonly_static("FeetPerSecond", &Measure::FeetPerSecond)
   ;
}